"""Subclass of SelectStaffDlg, which is generated by wxFormBuilder."""

import wx
import UI

# Implementing SelectStaffDlg
class LPMSelectStaffDlg( UI.SelectStaffDlg ):
	def __init__( self, parent ):
		UI.SelectStaffDlg.__init__( self, parent )

